### ISSUE TITLE
Error occurs when apps start

### ISSUE THREAD

**Issue by snaju2145** [sliceofcode/CheeseLauncher#7]
CheckJNI
02-17 17:38:02.059 12883-12883/me.cheesy.cheeselauncher I/CheeseLoader: Loading Minecraft: Pocket Edition libraries...
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Trying to load lib /data/app-lib/com.mojang.minecraftpe-1/libgnustl_shared.so 0x42d95058
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Added shared lib /data/app-lib/com.mojang.minecraftpe-1/libgnustl_shared.so 0x42d95058
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.mojang.minecraftpe-1/libgnustl_shared.so 0x42d95058, skipping init
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Trying to load lib /data/app-lib/com.mojang.minecraftpe-1/libfmod.so 0x42d95058
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Added shared lib /data/app-lib/com.mojang.minecraftpe-1/libfmod.so 0x42d95058
02-17 17:38:02.069 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Trying to load lib /data/app-lib/com.mojang.minecraftpe-1/libminecraftpe.so 0x42d95058
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher D/dalvikvm: Added shared lib /data/app-lib/com.mojang.minecraftpe-1/libminecraftpe.so 0x42d95058
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher W/dalvikvm: JNI WARNING: JNI function GetMethodID called with exception pending
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher W/dalvikvm:              in Ljava/lang/Runtime;.nativeLoad:(Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/String; (GetMethodID)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher W/dalvikvm: Pending exception is:
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm: java.lang.NoSuchMethodError: no method with name='launchUri' signature='(Ljava/lang/String;)V' in class Lcom/mojang/minecraftpe/MainActivity;
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.doLoad(Runtime.java:421)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.load(Runtime.java:331)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.System.load(System.java:512)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:104)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.Activity.performCreate(Activity.java:5249)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.access$900(ActivityThread.java:141)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5072)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm: "main" prio=5 tid=1 NATIVE
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41717e58 self=0x416378c0
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   | sysTid=12883 nice=0 sched=0/0 cgrp=apps handle=1074069844
02-17 17:38:02.129 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   | state=R schedstat=( 78272197 39595720 170 ) utm=1 stm=6 core=2
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #00  pc 0000132e  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #01  pc 00063502  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+33)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #02  pc 000574e8  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #03  pc 00057556  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #04  pc 0003b65c  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #05  pc 00043ad8  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #06  pc 0059f99a  /data/app-lib/com.mojang.minecraftpe-1/libminecraftpe.so (AppPlatform_android::init(_JavaVM*)+1741)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #07  pc 004dbf74  /data/app-lib/com.mojang.minecraftpe-1/libminecraftpe.so (JNI_OnLoad+71)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #08  pc 00052eae  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+465)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #09  pc 0006a62c  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #10  pc 000297e0  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #11  pc 00030c6c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #12  pc 0002e304  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #13  pc 00063714  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+391)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #14  pc 0006b626  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #15  pc 000297e0  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #16  pc 00030c6c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #17  pc 0002e304  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #18  pc 00063430  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+335)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #19  pc 0004cbb6  /system/lib/libdvm.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #20  pc 0004e328  /system/lib/libandroid_runtime.so
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #21  pc 0004f056  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*, bool)+357)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #22  pc 00001062  /system/bin/app_process
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:   #23  pc 0000e4c0  /system/lib/libc.so (__libc_init+47)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.doLoad(Runtime.java:421)
02-17 17:38:02.139 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.Runtime.load(Runtime.java:331)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.System.load(System.java:512)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:104)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.Activity.performCreate(Activity.java:5249)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.access$900(ActivityThread.java:141)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5072)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher E/dalvikvm: VM aborting
02-17 17:38:02.149 12883-12883/me.cheesy.cheeselauncher A/libc: Fatal signal 6 (SIGABRT) at 0x00003253 (code=-6), thread 12883 (.cheeselauncher)

**Comment by sliceofcode** [comment]
The launcher currently does not support Minecraft: Pocket Edition v0.14.0 and over.
